In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
maf = pd.read_csv('../../data_tables/maf_files/DLBCL_combined_699.hg38B.noPDE4DIP.noHISTartifacts.DRIVERSONLY.maf',
                 sep='\t')
maf

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (3,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,43,44,45,46,47,49,51,55,57,58,59,60,62,63,65,66,67,68,69,71,72,73,74,76,78,79,80,81,82,83,84,85,86,87,88,89,90,93,94,95,96,98,99,100,101,103,107,108,111,113,114,115,117,118,121,122,123,124,125,126,127,128,130,131,133,135,136,137,138,140,141,143,144,145,146,147,149,150,153,155,156,158,159,160,161,163,164,165,166,168,170,171,172,174,175,176,177,178,179,180,181,186,187,188,191,192,195,196,197,198,200,203,205,206,207,208,209,211,213,215,216,217,220,221,222,224,227,228,230,231,232,233,234,235,236,237,238,239,240,241,242,244,246,247,248,249,250,251,254,255,258,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,279,280,281,283,284,285,288,289,290,291,292,293,294,295,296,297,298,299,301,304,305,307,308,309,310,314,315,316,317,318,319,320,321,322,324,325,326,327,328,329,332,334,335,336,337,338,339,340,341,342,345,346,348,351,354,355,356,359,360,363,364,366,367,368,369,371,372,373,375,377,378,379,380,381,383,385,387,391,392,405,418,426,428,429,430,431,432,433,434,435,436,439,440,445,448,449,450,453,454,457,458,460,461,462,463,465,466,467,469,471,472,473,474,477,479,481,485,486,502,590,615,616,617,619,632,633,634,640,642,643,644,647,654,658,659,660,662,663,667,669,670,671,673,679,682,683,684,685,686,687,689,690,692,693,695,701,706,709,710,711,712,716,717,718,719,723,725,730,731,732,734,738,740,744,752,756,758,763,771,772,777,780,785,786,787,788,794,797,800,801,802,803,821,823,829,830,836,838,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,864,865,866,868,869,871,872,873,875,876,877,878,879,880,881,882) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,...,HGNC_UniProt ID(supplied by UniProt),HGNC_VEGA IDs,dbNSFP_GERP++_NR,dbNSFP_GERP++_RS,dbNSFP_GERP++_RS_rankscore,dbNSFP_fold-degenerate,dbNSFP_hg18_pos(1-coor),i_CGC_GeneID,i_COSMIC_n_overlapping_mutations,pon_loglike
0,KMT2D,8085,broad.mit.edu,37,12,49431742,49431742,+,Nonsense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BCL7A,605,broad.mit.edu,37,12,122460033,122460033,+,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KMT2D,8085,broad.mit.edu,37,12,49442443,49442443,+,Splice_Site,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EP300,2033,broad.mit.edu,37,22,41566459,41566459,+,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZNF423,23090,broad.mit.edu,37,16,49672594,49672594,+,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9359,PIM2,11040,broad.mit.edu,37,X,48775914,48775914,+,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.000000
9360,HIST1H1B,3009,broad.mit.edu,37,6,27834670,27834670,+,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.000000
9361,TMSB4X,7114,broad.mit.edu,37,X,12994413,12994413,+,Silent,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.000000
9362,NFKBIA,4792,broad.mit.edu,37,14,35872043,35872043,+,Frame_Shift_Del,DEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-20.000000
9363,POU2F2,5452,broad.mit.edu,37,19,42626287,42626287,+,Frame_Shift_Del,DEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-2.773105

In [4]:
btg2 = maf.loc[maf['Hugo_Symbol'] == 'BTG2']
btg2

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,...,HGNC_UniProt ID(supplied by UniProt),HGNC_VEGA IDs,dbNSFP_GERP++_NR,dbNSFP_GERP++_RS,dbNSFP_GERP++_RS_rankscore,dbNSFP_fold-degenerate,dbNSFP_hg18_pos(1-coor),i_CGC_GeneID,i_COSMIC_n_overlapping_mutations,pon_loglike
67,BTG2,7832,__UNKNOWN__,__UNKNOWN__,1,203276261,203276261,__UNKNOWN__,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,BTG2,7832,__UNKNOWN__,__UNKNOWN__,1,203274867,203274867,__UNKNOWN__,Missense_Mutation,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,BTG2,7832,__UNKNOWN__,__UNKNOWN__,1,203274878,203274878,__UNKNOWN__,Splice_Site,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,BTG2,7832,__UNKNOWN__,__UNKNOWN__,1,203276287,203276287,__UNKNOWN__,Silent,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,BTG2,7832,broad.mit.edu,37,1,203276231,203276231,+,Splice_Site,SNP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9096,BTG2,7832,Unknown,hg38,1,203274888,203274888,+,Intron,SNP,...,P78543,OTTHUMG00000035834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9203,BTG2,7832,Unknown,hg38,1,203274817,203274817,+,Missense_Mutation,SNP,...,P78543,OTTHUMG00000035834,4.66,4.66,0.58398,0,201541440,NaN,NaN,NaN
9204,BTG2,7832,Unknown,hg38,1,203274835,203274835,+,Missense_Mutation,SNP,...,P78543,OTTHUMG00000035834,4.66,2.79,0.32731,0,201541458,NaN,NaN,NaN
9205,BTG2,7832,Unknown,hg38,1,203274836,203274836,+,Silent,SNP,...,P78543,OTTHUMG00000035834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9275,BTG2,7832,Unknown,hg38,1,203274867,203274867,+,Missense_Mutation,SNP,...,P78543,OTTHUMG00000035834,4.4,4.4,0.53042,0,201541490,NaN,NaN,NaN

In [6]:
btg2_bed = btg2[['Chromosome', 'Start_position', 'End_position']]
btg2_bed.columns = [['chrom', 'chromStart', 'chromEnd']]
btg2_bed.to_csv('../../data_tables/maf_files/btg.bed', sep='\t', index=False)

     chrom chromStart   chromEnd
67       1  203276261  203276261
89       1  203274867  203274867
90       1  203274878  203274878
91       1  203276287  203276287
560      1  203276231  203276231
...    ...        ...        ...
9096     1  203274888  203274888
9203     1  203274817  203274817
9204     1  203274835  203274835
9205     1  203274836  203274836
9275     1  203274867  203274867

[260 rows x 3 columns]