In [1]:
import pandas as pd
import numpy as np

In [2]:
sv_df = pd.read_csv('/Users/twood/Desktop/DLBCL_Feature_Matrix_Generation/inputs_for_gene_sample_matrix/DLBCL_Shipp_Staudt.SVs.14-Dec-2021.txt',
                     sep='\t')
sv_df.head()

,Unnamed: 0,individual,num,str1,chr1,pos1,str2,chr2,pos2,class,...,CCF1CI_high,CCF1_MODEL,CCF1_multiplicity,CCF1_negativeLogLikelihood,CCF2,CCF2CI_low,CCF2CI_high,CCF2_MODEL,CCF2_multiplicity,CCF2_negativeLogLikelihood
0,22,DFCIDL001_DT,8.0,1.0,9.0,5078217.0,0.0,9.0,5388547.0,tandem_dup,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23,DFCIDL001_DT,10.0,0.0,9.0,5568155.0,0.0,9.0,5584951.0,inversion,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24,DFCIDL001_DT,19.0,1.0,12.0,122460270.0,0.0,14.0,106326737.0,inter_chr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25,DFCIDL001_DT,28.0,1.0,9.0,5078220.0,1.0,9.0,5883844.0,inversion,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,26,DFCIDL001_DT,32.0,0.0,16.0,10972248.0,1.0,16.0,11349188.0,deletion,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
for col in sv_df.columns:
    print(col)

Unnamed: 0
individual
num
str1
chr1
pos1
str2
chr2
pos2
class
span
tumreads
normreads
normpanelbins
min1
max1
range1
stdev1
min2
max2
range2
stdev2
gene1
site1
gene2
site2
fusion
fmapqzT1
fmapqzN1
fmapqzT2
fmapqzN2
nuwpT1
nuwpN1
nuwpT2
nuwpN2
zstdev1
zstdev2
quality
score
somatic
somatic_score
BPtry
dRpos1
dRpos2
BPresult
BPsomaticratio
approxflag
alg
id1
id2
t_alt_RP
t_alt_SR
n_alt_RP
t_dep
n_alt_SR
n_dep
Cluster
dRanger
snowman
lumpy
Breakmer
T_BPhit
T_BPpos1
T_diffpos1
T_BPpos2
T_diffpos2
T_SWreads
T_SWscore
T_firstseq
T_lenhomology
T_lenhomology_soft
T_lenforeign
T_foreignseq
T_BWAreads
N_BPhit
N_BPpos1
N_diffpos1
N_BPpos2
N_diffpos2
N_SWreads
N_SWscore
N_firstseq
N_lenhomology
N_lenhomology_soft
N_lenforeign
N_foreignseq
N_BWAreads
VCF_TALT
VCF_TALT_RP
VCF_TALT_SR
VCF_TREF
VCF_TREF_RP
VCF_TREF_SR
VCF_TREF1
VCF_TREF1_RP
VCF_TREF1_SR
VCF_TREF2
VCF_TREF2_RP
VCF_TREF2_SR
VCF_NALT
VCF_NALT_RP
VCF_NALT_SR
VCF_NREF
VCF_NREF_RP
VCF_NREF_SR
VCF_NREF1
VCF_NREF1_RP
VCF_NREF1_SR
VCF_NREF2
VCF_NREF2_RP
VCF_NREF2_SR
VCF_QUAL
VCF_HOMLEN
VCF_HOMSEQ
VCF_FORLEN
VCF_FORSEQ
VCF_POS1
VCF_ALT1
VCF_POS2
VCF_ALT2
Nalg
TargetID1
TargetID2
NTarget
call
x1
x2
gender_M_F
NCN1
NCN2
VCF_VAF
VCF_VAF_95CI_low
VCF_VAF_95CI_high
VCF_VAF_32CI_low
VCF_VAF_32CI_high
pair_id
purity
CN1
CNT1
AF2CCF1
CN2
CNT2
AF2CCF2
CCF_SCNA1
CCF_SCNA2
NA_SCNA1
NA_SCNA2
NB_SCNA1
NB_SCNA2
CCF0
CCF0_break1
CCF0_break2
CCF0_95CI_low
CCF0_95CI_high
CCF
CCFCI_low
CCFCI_high
CCF_MODEL
CCF_multiplicity
CCF_negativeLogLikelihood
targ1
targ2
VAF1
VAF2
VCF_VAF1
VCF_VAF1_95CI_low
VCF_VAF1_95CI_high
VCF_VAF2
VCF_VAF2_95CI_low
VCF_VAF2_95CI_high
tau1
tau2
x1w
x2w
CCF1
CCF1CI_low
CCF1CI_high
CCF1_MODEL
CCF1_multiplicity
CCF1_negativeLogLikelihood
CCF2
CCF2CI_low
CCF2CI_high
CCF2_MODEL
CCF2_multiplicity
CCF2_negativeLogLikelihood

In [4]:
sv_df['gene1']

0          JAK2
1      PDCD1LG2
2         BCL7A
3          JAK2
4         CIITA
         ...
577         MYC
578        BCL6
579        BCL2
580         MYC
581        BCL2
Name: gene1, Length: 582, dtype: object

In [5]:
sv_df['tumreads']

0       6.0
1      82.0
2       9.0
3       3.0
4       6.0
       ...
577     NaN
578     NaN
579     NaN
580     NaN
581     NaN
Name: tumreads, Length: 582, dtype: float64

In [6]:
maf = pd.read_csv('../../data_tables/maf_files/DLBCL_combined_700.hg38B.trimmed.maf', sep='\t')
maf.head()

,Hugo_Symbol,Chromosome,Start_position,End_position,Tumor_Sample_Barcode,Variant_Classification,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,t_alt_count,t_ref_count,Protein_Change
0,CBFA2T2,20,32232306,32232306,DFCIDL003_DT,Missense_Mutation,C,C,T,40.0,44.0,p.R557W
1,MICU2,13,22069394,22069394,DFCIDL003_DT,Missense_Mutation,G,G,C,12.0,23.0,p.T369S
2,UGT2B11,4,70079916,70079916,DFCIDL003_DT,Silent,A,A,T,36.0,87.0,p.T175T
3,ODC1,2,10583919,10583919,DFCIDL003_DT,Missense_Mutation,G,G,A,56.0,58.0,p.R165C
4,LIN28B,6,105406020,105406020,DFCIDL003_DT,Silent,G,G,A,7.0,65.0,p.E19E

In [7]:
sig_genes = pd.read_csv('../../data_tables/qval_dfs/fisher_exact_5x2_17-Aug-2022.combined.tsv', 
                        sep='\t', index_col=0)
sig_genes = sig_genes.loc[sig_genes['q'] <= 0.10].index

sig_genes

Index(['SV.BCL6', 'DTX1', 'CD70', 'TNFAIP3', 'NOTCH2', 'BCL10', 'CD58',
       'X5Q.AMP', 'B2M', 'UBE2A',
       ...
       'TOX', 'X18Q22.2.AMP', 'HLA.C', 'VMP1', 'X6Q14.1.DEL', 'SF3B1',
       'ZC3H12A', 'ATP2A2', 'X1Q32.1.AMP', 'X6P21.33.DEL'],
      dtype='object', name='gene', length=162)

In [8]:
amps = [x for x in sig_genes if '.AMP' in x]
dels = [x for x in sig_genes if '.DEL' in x]
svs = [x for x in sig_genes if 'SV.' in x]

mutations = [x for x in sig_genes if (x not in amps) and (x not in dels) and (x not in svs)]

In [9]:
maf['Variant_Classification'].value_counts()

Missense_Mutation           108304
Silent                       50971
Intron                       16753
Splice_Site                   6430
Nonsense_Mutation             5292
RNA                           4266
Frame_Shift_Del               3014
Frame_Shift_Ins               1702
5'UTR                         1422
In_Frame_Del                  1241
3'UTR                         1231
IGR                            795
5'Flank                        611
In_Frame_Ins                   577
lincRNA                        568
Start_Codon_SNP                243
Nonstop_Mutation               148
De_novo_Start_InFrame           42
De_novo_Start_OutOfFrame        41
Start_Codon_Ins                 15
Stop_Codon_Del                  14
Start_Codon_Del                 12
Stop_Codon_Ins                   8
Name: Variant_Classification, dtype: int64

In [10]:
# if maf changes (?) make sure you re-do these. Whitelisting coding is a bit safer than blacklisting noncoding,
# since UNDETERMINED & other things may show up that we don't want.
coding = ['Missense_Mutation', 'Splice_Site', 'Nonsense_Mutation', 'Frame_Shift_Del', 'Frame_Shift_Ins',
          'In_Frame_Del', 'In_Frame_Ins', 'Start_Codon_SNP', 'Nonstop_Mutation', 'De_novo_Start_InFrame',
          'De_novo_Start_OutOfFrame', 'Start_Codon_Ins', 'Stop_Codon_Del', 'Start_Codon_Del', 'Stop_Codon_Ins']

In [11]:
gsm = pd.read_csv('../../data_tables/gsm/DLBCL_Staudt_Shipp_CL.for_classifier_training.classifier_subset.fix_sv.fix_ploidy.17-Aug-2022.txt',
                 sep='\t', index_col=0)
gsm = gsm.loc[sig_genes].astype(float).astype(int)
gsm.head()

,DLBCL11574,DLBC_FF_8046_TP_NB,DLBCL10848,DLBCL10515,DLBCL11484,DLBCL_RICOVER_866,DLBCL_C_D_1109_NULLPAIR,DLBCL11346,DLBCL11581,DLBCL10957,...,DLBCL11575,DLBCL_C_D_1142_NULLPAIR,DLBCL11562,DLBCL_LS2305,DLBCL_C_D_PAIR2,DLBCL_C_D_PAIR20,DLBCL_C_D_PAIR22,DLBCL_C_D_PAIR23,DLBCL_C_D_PAIR5,DLBCL_C_D_PAIR9
gene,,,,,,,,,,,,,,,,,,,,,
SV.BCL6,0,0,3,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DTX1,0,0,0,2,0,2,0,0,0,2,...,0,2,0,0,0,0,2,0,0,0
CD70,0,0,0,2,0,0,2,0,0,0,...,0,0,0,0,0,0,0,2,0,0
TNFAIP3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2,0,0
NOTCH2,0,0,0,2,0,0,0,0,0,2,...,2,0,0,0,0,0,0,2,0,0

In [12]:
maf_coding = maf.loc[maf['Variant_Classification'].isin(coding + ['Silent'])]
maf_coding

,Hugo_Symbol,Chromosome,Start_position,End_position,Tumor_Sample_Barcode,Variant_Classification,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,t_alt_count,t_ref_count,Protein_Change
0,CBFA2T2,20,32232306,32232306,DFCIDL003_DT,Missense_Mutation,C,C,T,40.0,44.0,p.R557W
1,MICU2,13,22069394,22069394,DFCIDL003_DT,Missense_Mutation,G,G,C,12.0,23.0,p.T369S
2,UGT2B11,4,70079916,70079916,DFCIDL003_DT,Silent,A,A,T,36.0,87.0,p.T175T
3,ODC1,2,10583919,10583919,DFCIDL003_DT,Missense_Mutation,G,G,A,56.0,58.0,p.R165C
4,LIN28B,6,105406020,105406020,DFCIDL003_DT,Silent,G,G,A,7.0,65.0,p.E19E
...,...,...,...,...,...,...,...,...,...,...,...,...
203695,FLI1,11,128564172,128564173,DLBCL_C_D_PAIR9,Splice_Site,GT,GT,-,NaN,NaN,NaN
203696,NFKBIA,14,35872043,35872043,DLBCL_C_D_PAIR9,Frame_Shift_Del,G,G,-,NaN,NaN,p.A190fs
203697,ELMSAN1,14,74205819,74205826,DLBCL_C_D_PAIR9,Frame_Shift_Del,TGTCCCAG,TGTCCCAG,-,NaN,NaN,p.LGQ296fs
203698,PRKCB,16,23847649,23847649,DLBCL_C_D_PAIR9,Frame_Shift_Del,C,C,-,NaN,NaN,p.S51fs
203699,POU2F2,19,42626287,42626287,DLBCL_C_D_PAIR9,Frame_Shift_Del,G,G,-,NaN,NaN,p.P59fs

In [13]:
gsm_ac = pd.DataFrame(np.nan, index=mutations, columns=gsm.columns)
gsm_ac

,DLBCL11574,DLBC_FF_8046_TP_NB,DLBCL10848,DLBCL10515,DLBCL11484,DLBCL_RICOVER_866,DLBCL_C_D_1109_NULLPAIR,DLBCL11346,DLBCL11581,DLBCL10957,...,DLBCL11575,DLBCL_C_D_1142_NULLPAIR,DLBCL11562,DLBCL_LS2305,DLBCL_C_D_PAIR2,DLBCL_C_D_PAIR20,DLBCL_C_D_PAIR22,DLBCL_C_D_PAIR23,DLBCL_C_D_PAIR5,DLBCL_C_D_PAIR9
DTX1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TNFAIP3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NOTCH2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BCL10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HLA.C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VMP1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SF3B1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZC3H12A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATP2A2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
maf_coding.loc[:, 'Hugo_Symbol'] = maf_coding.loc[:, 'Hugo_Symbol'].str.replace('-', '.')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [15]:
myd88_l265p = {'p.L265P', 'p.*160R', 'p.L273P'}
for col in gsm.columns:
    sample_col = gsm[col]
    sample = sample_col.name
    events = sample_col[sample_col != 0]
    maf_s = maf_coding.loc[maf_coding['Tumor_Sample_Barcode'] == sample]
    
    for e in events.index:
        if e not in mutations:
            continue
            
        val = events[e]
        
        if e == 'MYD88':
            continue
        elif e == 'MYD88.L265P':
            maf_e = maf_s.loc[(maf_s['Hugo_Symbol'] == 'MYD88') & 
                              (maf_s['Protein_Change'].isin(myd88_l265p))]
        elif e == 'MYD88.OTHER':
            maf_e = maf_s.loc[(maf_s['Hugo_Symbol'] == 'MYD88') & 
                              ~(maf_s['Protein_Change'].isin(myd88_l265p))]
        else:
            maf_e = maf_s.loc[maf_s['Hugo_Symbol'] == e]
        
        if val == 1:
            maf_e = maf_e.loc[maf_e['Variant_Classification'] == 'Silent']
        else:
            maf_e = maf_e.loc[maf_e['Variant_Classification'] != 'Silent']
            
        max_talt = maf_e['t_alt_count'].max()
        
        gsm_ac.loc[e, sample] = max_talt

In [16]:
gsm_ac

,DLBCL11574,DLBC_FF_8046_TP_NB,DLBCL10848,DLBCL10515,DLBCL11484,DLBCL_RICOVER_866,DLBCL_C_D_1109_NULLPAIR,DLBCL11346,DLBCL11581,DLBCL10957,...,DLBCL11575,DLBCL_C_D_1142_NULLPAIR,DLBCL11562,DLBCL_LS2305,DLBCL_C_D_PAIR2,DLBCL_C_D_PAIR20,DLBCL_C_D_PAIR22,DLBCL_C_D_PAIR23,DLBCL_C_D_PAIR5,DLBCL_C_D_PAIR9
DTX1,NaN,NaN,NaN,8.0,NaN,13.0,NaN,NaN,NaN,12.0,...,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD70,NaN,NaN,NaN,5.0,NaN,NaN,13.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TNFAIP3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NOTCH2,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,14.0,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BCL10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HLA.C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VMP1,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SF3B1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
ZC3H12A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATP2A2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
gsm_sv_reads = pd.DataFrame(np.nan, index=svs, columns=gsm_ac.columns)
gsm_sv_reads

,DLBCL11574,DLBC_FF_8046_TP_NB,DLBCL10848,DLBCL10515,DLBCL11484,DLBCL_RICOVER_866,DLBCL_C_D_1109_NULLPAIR,DLBCL11346,DLBCL11581,DLBCL10957,...,DLBCL11575,DLBCL_C_D_1142_NULLPAIR,DLBCL11562,DLBCL_LS2305,DLBCL_C_D_PAIR2,DLBCL_C_D_PAIR20,DLBCL_C_D_PAIR22,DLBCL_C_D_PAIR23,DLBCL_C_D_PAIR5,DLBCL_C_D_PAIR9
SV.BCL6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SV.BCL2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SV.MYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
sv_df['VCF_TALT']

0        6.0
1      229.0
2        8.0
3       70.0
4       25.0
       ...
577      NaN
578      NaN
579      NaN
580      NaN
581      NaN
Name: VCF_TALT, Length: 582, dtype: float64

In [19]:
for col in gsm.columns:
    sample_col = gsm[col]
    sample = sample_col.name
    events = sample_col[['SV.BCL2', 'SV.BCL6', 'SV.MYC']]
    if not sum(events):
        continue
        
    sv_s = sv_df.loc[sv_df['individual'] == sample]
    
    if not len(sv_s.index):
        continue
        
    for e in events.index:
        file_event = e.replace('SV.', '')
        val = events[e]
        
        if not val:
            continue
        
        sv_e = sv_s.loc[(sv_s['gene1'] == file_event) | (sv_s['gene2'] == file_event)]
        max_treads = sv_e['VCF_TALT'].max()
        gsm_sv_reads.loc[e, sample] = max_treads
        
        if np.isnan(max_treads):
            print(sample, e)

DLBCL10848 SV.BCL6
DLBCL10515 SV.BCL6
DLBCL11666 SV.BCL2
DLBCL11573 SV.BCL2
DLBCL11525 SV.BCL2
DLBCL11525 SV.MYC
DLBCL10947 SV.BCL6
DLBCL10897 SV.BCL6
DLBCL11680 SV.BCL2
DLBCL10548 SV.BCL6
DLBCL11482 SV.MYC
DLBCL11669 SV.BCL2
DLBCL11001 SV.MYC
DLBCL11656 SV.BCL2
DLBCL11191 SV.BCL6
DLBCL11461 SV.BCL6
DLBCL11520 SV.BCL6
DLBCL10484 SV.MYC
DLBCL10491 SV.MYC
DLBCL11566 SV.BCL2
DLBCL10843 SV.BCL6
DLBCL11677 SV.BCL6
DLBCL10465 SV.BCL2
DLBCL10459 SV.BCL2
DLBCL11443 SV.BCL6
DLBCL10450 SV.MYC
DLBCL10894 SV.BCL6
DLBCL11464 SV.BCL6
DLBCL10846 SV.BCL6
DLBCL11496 SV.BCL6
DLBCL10927 SV.BCL6
DLBCL11470 SV.BCL6
DLBCL11662 SV.BCL6
DLBCL11661 SV.MYC
DLBCL11672 SV.BCL2
DLBCL10928 SV.BCL6
DLBCL10978 SV.MYC
DLBCL11539 SV.BCL6
DLBCL10887 SV.MYC
DLBCL10542 SV.BCL6
DLBCL11512 SV.BCL6
DLBCL10514 SV.BCL2
DLBCL10975 SV.BCL6
DLBCL10834 SV.BCL6
DLBCL11515 SV.MYC
DLBCL10782 SV.BCL6
DLBCL10555 SV.BCL2
DLBCL10549 SV.MYC
DLBCL11664 SV.BCL6
DLBCL11655 SV.BCL6
DLBCL11498 SV.BCL6
DLBCL11507 SV.BCL6
DLBCL10488 SV.BCL6
DLBCL10525 SV.BCL6
DLBCL10945 SV.BCL6
DLBCL11676 SV.BCL6
DLBCL11569 SV.BCL2
DLBCL11569 SV.MYC
DLBCL11558 SV.BCL2
DLBCL11679 SV.BCL6
DLBCL10458 SV.BCL6
DLBCL11486 SV.BCL6
DLBCL10451 SV.BCL2
DLBCL10451 SV.BCL6
DLBCL11454 SV.BCL6
DLBCL11478 SV.BCL6
DLBCL11437 SV.BCL6
DLBCL11526 SV.BCL6
DLBCL11527 SV.BCL2
DLBCL10884 SV.BCL6
DLBCL10896 SV.BCL6
DLBCL11685 SV.BCL2
DLBCL10996 SV.BCL6
DLBCL10912 SV.BCL6
DLBCL10918 SV.BCL6
DLBCL10462 SV.BCL6
DLBCL11513 SV.MYC
DLBCL10930 SV.BCL6
DLBCL10931 SV.BCL6
DLBCL10879 SV.BCL2
DLBCL10950 SV.BCL6
DLBCL11205 SV.BCL6
DLBCL11242 SV.BCL6
DLBCL10968 SV.BCL6
DLBCL11591 SV.BCL2
DLBCL10565 SV.BCL2
DLBCL11458 SV.BCL6
DLBCL10487 SV.BCL6
DLBCL10492 SV.BCL6
DLBCL10993 SV.BCL6
DLBCL11537 SV.BCL6
DLBCL10498 SV.BCL2
DLBCL10498 SV.MYC
DLBCL11518 SV.BCL6
DLBCL11501 SV.BCL6
DLBCL10850 SV.BCL6
DLBCL10480 SV.BCL6
DLBCL10501 SV.BCL2
DLBCL11474 SV.BCL6
DLBCL10913 SV.BCL6
DLBCL10464 SV.BCL2
DLBCL11473 SV.BCL6
DLBCL11477 SV.BCL6
DLBCL11542 SV.BCL2
DLBCL11488 SV.BCL6
DLBCL10483 SV.BCL2
DLBCL10483 SV.MYC
DLBCL10907 SV.BCL6
DLBCL11670 SV.BCL2
DLBCL10554 SV.MYC
DLBCL11651 SV.BCL2
DLBCL10564 SV.BCL2
DLBCL11675 SV.BCL2
DLBCL10966 SV.BCL6
DLBCL11678 SV.BCL2
DLBCL11678 SV.MYC
DLBCL10466 SV.BCL2
DLBCL10466 SV.MYC
DLBCL10518 SV.MYC
DLBCL10972 SV.BCL6
DLBCL10495 SV.BCL6
DLBCL_C_D_1148_NULLPAIR SV.BCL2
DLBCL11428 SV.BCL2
DLBCL10833 SV.BCL6
DLBCL10833 SV.MYC
DLBCL10552 SV.BCL6
DLBCL11429 SV.BCL6
DLBCL10959 SV.BCL6
DLBCL11469 SV.BCL2
DLBCL10780 SV.BCL2
DLBCL10935 SV.BCL6
DLBCL11511 SV.BCL6
DLBCL10509 SV.BCL6
DLBCL11572 SV.BCL2
DLBCL10481 SV.BCL2
DLBCL11530 SV.BCL2
DLBCL11585 SV.BCL2
DLBCL11532 SV.BCL2
DLBCL10546 SV.BCL6
DLBCL11559 SV.BCL2
DLBCL10473 SV.MYC
DLBCL10476 SV.BCL2
DLBCL11579 SV.MYC
DLBCL11540 SV.BCL6
DLBCL11584 SV.BCL2
DLBCL10504 SV.BCL6
DLBCL10506 SV.BCL6
DLBCL11452 SV.BCL6
DLBCL11586 SV.BCL6
DLBCL11506 SV.BCL6
DLBCL11193 SV.BCL2
DLBCL11193 SV.BCL6
DLBCL10537 SV.BCL2
DLBCL11508 SV.BCL6
DLBCL10942 SV.BCL6
DLBCL11684 SV.MYC
DLBCL11575 SV.BCL2
DLBCL11562 SV.BCL2

In [20]:
gsm_mut_svs = pd.concat([gsm_ac, gsm_sv_reads])
gsm_mut_svs

,DLBCL11574,DLBC_FF_8046_TP_NB,DLBCL10848,DLBCL10515,DLBCL11484,DLBCL_RICOVER_866,DLBCL_C_D_1109_NULLPAIR,DLBCL11346,DLBCL11581,DLBCL10957,...,DLBCL11575,DLBCL_C_D_1142_NULLPAIR,DLBCL11562,DLBCL_LS2305,DLBCL_C_D_PAIR2,DLBCL_C_D_PAIR20,DLBCL_C_D_PAIR22,DLBCL_C_D_PAIR23,DLBCL_C_D_PAIR5,DLBCL_C_D_PAIR9
DTX1,NaN,NaN,NaN,8.0,NaN,13.0,NaN,NaN,NaN,12.0,...,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CD70,NaN,NaN,NaN,5.0,NaN,NaN,13.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TNFAIP3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NOTCH2,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,14.0,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BCL10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZC3H12A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATP2A2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SV.BCL6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SV.BCL2,NaN,NaN,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN
SV.MYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
gsm_mut_svs.to_csv('../../data_tables/gsm/gsm_17-Aug-2022_altcounts.tsv', sep='\t')